import Cocoa
import Foundation
import Security
import VeloxCore
import os.log

private struct ClipboardSource {
    let displayName: String
    let process: ProcessContext
}

private struct ClipboardEventPayload: Encodable {
    let sourceApplication: String
    let signingId: String?
    let teamId: String?
    let executablePath: String
    let pid: Int32
    let codesigningFlags: UInt32
    let isPlatformBinary: Bool
    let contentTypes: [String]
    let itemCount: Int
    let cleared: Bool
}

private struct PendingBrowserClipboardTransfer {
    let pasteboardChangeCount: Int
    let filePaths: [String]
}

@MainActor
final class PasteboardMonitor {
    private let logger = Logger(subsystem: "co.velox.macdlp", category: "PasteboardMonitor")
    private let controlClient: ExtensionControlClient
    private var timer: Timer?
    private var activationObserver: NSObjectProtocol?
    private var lastChangeCount = 0
    private var isMonitoring = false
    private var policyEngine: PolicyEngine
    private var pendingBrowserTransfer: PendingBrowserClipboardTransfer?

    init(controlClient: ExtensionControlClient) {
        self.controlClient = controlClient
        let policyPath = PolicyManager.defaultPolicyPath
        if let data = try? Data(contentsOf: URL(fileURLWithPath: policyPath)),
           let policy = try? VeloxPolicy.decodeStrict(from: data) {
            self.policyEngine = PolicyEngine(policy: policy)
        } else {
            self.policyEngine = PolicyEngine(policy: VeloxPolicy(
                policyVersion: 1,
                applicationControl: ApplicationControlConfig(mode: .auditOnly),
                webUploadControl: WebUploadControlConfig(mode: .enforce),
                clipboardControl: ClipboardControlConfig(mode: .disabled)
            ))
        }
        self.lastChangeCount = NSPasteboard.general.changeCount
    }

    public func start() {
        guard !isMonitoring else { return }
        isMonitoring = true
        lastChangeCount = NSPasteboard.general.changeCount

        // NSPasteboard has no public change notification. Polling changeCount is
        // inexpensive because clipboard contents are read only after it changes.
        timer = Timer.scheduledTimer(withTimeInterval: 0.10, repeats: true) { [weak self] _ in
            Task { @MainActor [weak self] in
                self?.checkPasteboard()
            }
        }

        activationObserver = NSWorkspace.shared.notificationCenter.addObserver(
            forName: NSWorkspace.didActivateApplicationNotification,
            object: nil,
            queue: .main
        ) { [weak self] _ in
            Task { @MainActor [weak self] in
                self?.checkPasteboard()
            }
        }

        logger.info("PasteboardMonitor started with 100ms change detection.")
    }

    public func stop() {
        timer?.invalidate()
        timer = nil
        if let activationObserver {
            NSWorkspace.shared.notificationCenter.removeObserver(activationObserver)
            self.activationObserver = nil
        }
        pendingBrowserTransfer = nil
        isMonitoring = false
        logger.info("PasteboardMonitor stopped.")
    }

    public func reloadPolicy() {
        let policyPath = PolicyManager.defaultPolicyPath
        if let data = try? Data(contentsOf: URL(fileURLWithPath: policyPath)),
           let policy = try? VeloxPolicy.decodeStrict(from: data) {
            policyEngine.updatePolicy(policy)
        }
    }

    public func checkPasteboard() {
        let pasteboard = NSPasteboard.general
        let currentChangeCount = pasteboard.changeCount

        if currentChangeCount != lastChangeCount {
            lastChangeCount = currentChangeCount
            handleNewClipboardContent(on: pasteboard, changeCount: currentChangeCount)
        }

        enforcePendingBrowserTransferIfNeeded(on: pasteboard)
    }

    private func handleNewClipboardContent(on pasteboard: NSPasteboard, changeCount: Int) {
        let itemCount = pasteboard.pasteboardItems?.count ?? 0
        let filePaths = clipboardFilePaths(from: pasteboard)
        let contentTypes = clipboardTypeSummary(from: pasteboard, filePaths: filePaths)

        // Ignore an empty clipboard, including the change generated by our own clear.
        guard itemCount > 0, !contentTypes.isEmpty else {
            pendingBrowserTransfer = nil
            return
        }

        reloadPolicy()
        let source = currentClipboardSource()
        let decision = policyEngine.evaluateClipboardCopy(source: source.process)

        if decision.shouldClearPasteboard {
            pasteboard.clearContents()
            lastChangeCount = pasteboard.changeCount
            pendingBrowserTransfer = nil
            logger.warning(
                "Blocked clipboard copy from \(source.displayName, privacy: .public) (\(source.process.signingId ?? "unknown", privacy: .public))"
            )

            let summary = "\(contentTypes.joined(separator: ", ")) · \(itemCount) item\(itemCount == 1 ? "" : "s")"
            VeloxNotificationManager.shared.postBlockedNotification(
                module: "clipboard-control",
                action: "copy",
                target: summary,
                detail: source.displayName
            )
            reportClipboardEvent(
                source: source,
                contentTypes: contentTypes,
                itemCount: itemCount,
                cleared: true
            )
            return
        }

        if policyEngine.currentPolicy().clipboardControl.mode != .disabled {
            reportClipboardEvent(
                source: source,
                contentTypes: contentTypes,
                itemCount: itemCount,
                cleared: false
            )
        }

        pendingBrowserTransfer = filePaths.isEmpty ? nil : PendingBrowserClipboardTransfer(
            pasteboardChangeCount: changeCount,
            filePaths: filePaths
        )
    }

    /// Preserves the existing browser-upload clipboard guard independently of
    /// Clipboard Control. A copied file is evaluated when a browser becomes active.
    private func enforcePendingBrowserTransferIfNeeded(on pasteboard: NSPasteboard) {
        guard let pendingBrowserTransfer else { return }
        guard pasteboard.changeCount == pendingBrowserTransfer.pasteboardChangeCount else {
            self.pendingBrowserTransfer = nil
            return
        }
        guard let frontmostApp = NSWorkspace.shared.frontmostApplication,
              let bundleId = frontmostApp.bundleIdentifier,
              PolicyEngine.isSupportedBrowserBundleId(bundleId) else { return }

        reloadPolicy()
        let decision = policyEngine.evaluateClipboardContent(
            filePaths: pendingBrowserTransfer.filePaths
        )
        self.pendingBrowserTransfer = nil

        guard decision.shouldBlock || decision.decisionString == "would-block" else { return }

        let blockedNames = decision.blockedPaths.map { ($0 as NSString).lastPathComponent }
        if decision.shouldBlock {
            pasteboard.clearContents()
            lastChangeCount = pasteboard.changeCount
            logger.warning("Blocked clipboard file transfer of \(blockedNames) to \(bundleId)")
            VeloxNotificationManager.shared.postBlockedNotification(
                module: "web-upload-control",
                action: "clipboard-paste",
                target: blockedNames.joined(separator: ", "),
                detail: bundleId
            )
        } else {
            logger.info("Audited clipboard file transfer of \(blockedNames) to \(bundleId)")
        }

        let payload: [String: Any] = [
            "fileNames": blockedNames,
            "interaction": "paste",
            "pageURL": bundleId,
            "blocked": decision.shouldBlock
        ]
        if let jsonData = try? JSONSerialization.data(withJSONObject: payload),
           let jsonString = String(data: jsonData, encoding: .utf8) {
            controlClient.recordBrowserUploadAttempt(jsonString) { _ in }
        }
    }

    private func clipboardFilePaths(from pasteboard: NSPasteboard) -> [String] {
        var filePaths = Set<String>()

        if let urls = pasteboard.readObjects(
            forClasses: [NSURL.self],
            options: [.urlReadingFileURLsOnly: true]
        ) as? [URL] {
            for url in urls where url.isFileURL {
                filePaths.insert(url.path)
            }
        }

        if let filenames = pasteboard.propertyList(
            forType: NSPasteboard.PasteboardType("NSFilenamesPboardType")
        ) as? [String] {
            filePaths.formUnion(filenames)
        }

        return filePaths.sorted()
    }

    /// Returns only coarse categories. Actual text, images, and file paths are
    /// intentionally excluded from clipboard telemetry.
    private func clipboardTypeSummary(
        from pasteboard: NSPasteboard,
        filePaths: [String]
    ) -> [String] {
        var categories = Set<String>()
        if !filePaths.isEmpty { categories.insert("files") }

        for type in pasteboard.types ?? [] {
            let raw = type.rawValue.lowercased()
            if raw.contains("file-url") || raw.contains("filenames") {
                categories.insert("files")
            } else if raw.contains("image") || raw.contains("png") || raw.contains("tiff") {
                categories.insert("image")
            } else if raw.contains("html") || raw.contains("rtf") {
                categories.insert("formatted-text")
            } else if raw.contains("text") || raw.contains("string") || raw.contains("utf8") {
                categories.insert("text")
            }
        }

        if categories.isEmpty, !(pasteboard.types ?? []).isEmpty {
            categories.insert("application-data")
        }
        return categories.sorted()
    }

    private func currentClipboardSource() -> ClipboardSource {
        guard let application = NSWorkspace.shared.frontmostApplication else {
            return ClipboardSource(
                displayName: "Unknown Application",
                process: ProcessContext(
                    pid: 0,
                    parentPid: 0,
                    uid: getuid(),
                    signingId: nil,
                    teamId: nil,
                    isPlatformBinary: false,
                    cdhash: nil,
                    executablePath: "/usr/bin/unknown"
                )
            )
        }

        let identity = codeIdentity(for: application.processIdentifier)
        let executablePath = application.executableURL?.path
            ?? application.bundleURL?.path
            ?? "/usr/bin/unknown"
        let signingId = identity.signingId ?? application.bundleIdentifier
        let displayName = application.localizedName
            ?? application.bundleIdentifier
            ?? (executablePath as NSString).lastPathComponent

        return ClipboardSource(
            displayName: displayName,
            process: ProcessContext(
                pid: application.processIdentifier,
                parentPid: 0,
                uid: getuid(),
                signingId: signingId,
                teamId: identity.teamId,
                isPlatformBinary: identity.isPlatformBinary,
                cdhash: nil,
                executablePath: executablePath,
                codesigningFlags: identity.codesigningFlags
            )
        )
    }

    private func codeIdentity(for pid: pid_t) -> (
        signingId: String?,
        teamId: String?,
        isPlatformBinary: Bool,
        codesigningFlags: UInt32
    ) {
        let attributes = [kSecGuestAttributePid: NSNumber(value: pid)] as CFDictionary
        var dynamicCode: SecCode?
        guard SecCodeCopyGuestWithAttributes(nil, attributes, [], &dynamicCode) == errSecSuccess,
              let dynamicCode else {
            return (nil, nil, false, 0)
        }

        var signingInformation: CFDictionary?
        var staticCode: SecStaticCode?
        guard SecCodeCopyStaticCode(dynamicCode, [], &staticCode) == errSecSuccess,
              let staticCode,
              SecCodeCopySigningInformation(
                  staticCode,
                  SecCSFlags(rawValue: kSecCSSigningInformation),
                  &signingInformation
              ) == errSecSuccess,
              let values = signingInformation as? [String: Any] else {
            return (nil, nil, false, 0)
        }

        let flags = (values[kSecCodeInfoFlags as String] as? NSNumber)?.uint32Value ?? 0
        let platformBinaryFlag: UInt32 = 0x0400_0000
        return (
            values[kSecCodeInfoIdentifier as String] as? String,
            values[kSecCodeInfoTeamIdentifier as String] as? String,
            (flags & platformBinaryFlag) != 0,
            flags
        )
    }

    private func reportClipboardEvent(
        source: ClipboardSource,
        contentTypes: [String],
        itemCount: Int,
        cleared: Bool
    ) {
        let payload = ClipboardEventPayload(
            sourceApplication: source.displayName,
            signingId: source.process.signingId,
            teamId: source.process.teamId,
            executablePath: source.process.executablePath,
            pid: source.process.pid,
            codesigningFlags: source.process.codesigningFlags,
            isPlatformBinary: source.process.isPlatformBinary,
            contentTypes: contentTypes,
            itemCount: min(itemCount, 100),
            cleared: cleared
        )
        guard let data = try? JSONEncoder().encode(payload),
              let json = String(data: data, encoding: .utf8) else { return }
        controlClient.recordClipboardEvent(json) { _ in }
    }
}
